package qingyun.ele.domain.db;
// Generated 2017-6-25 11:08:16 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerData generated by hbm2java
 */
@Entity
@Table(name="customer_data"
    ,catalog="ele"
)
public class CustomerData  implements java.io.Serializable {


     private Long id;
     private Long idCustomer;
     private String customerName;
     private String customerCode;
     private String timeDuration;
     private Float capacity;
     private String customerAddress;
   
     private String inverterSn;
     private String channel;
     private Float temp;
     private Date CTime;
     private Float vpv1;
     private Float vpv2;
     private Float vpv3;
     private Float lpv1;
     private Float lpv2;
     private Float lpv3;
     private Float vac1;
     private Float vac2;
     private Float vac3;
     private Float lac1;
     private Float lac2;
     private Float lac3;
     private Float pac1;
     private Float pac2;
     private Float pac3;
     private Float fac;
     private Float todayEne;
     private Float totalEne;

    public CustomerData() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="id_customer")
    public Long getIdCustomer() {
        return this.idCustomer;
    }
    
    public void setIdCustomer(Long idCustomer) {
        this.idCustomer = idCustomer;
    }
    
    @Column(name="customer_name", length=64)
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    
    @Column(name="customer_code", length=64)
    public String getCustomerCode() {
        return this.customerCode;
    }
    
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }
    
    @Column(name="time_duration", length=64)
    public String getTimeDuration() {
        return this.timeDuration;
    }
    
    public void setTimeDuration(String timeDuration) {
        this.timeDuration = timeDuration;
    }
    
    @Column(name="capacity", precision=12, scale=0)
    public Float getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(Float capacity) {
        this.capacity = capacity;
    }
    
    @Column(name="customer_address", length=128)
    public String getCustomerAddress() {
        return this.customerAddress;
    }
    
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }


    
    @Column(name="inverter_sn", length=64)
    public String getInverterSn() {
        return this.inverterSn;
    }
    
    public void setInverterSn(String inverterSn) {
        this.inverterSn = inverterSn;
    }
    
    @Column(name="channel", length=64)
    public String getChannel() {
        return this.channel;
    }
    
    public void setChannel(String channel) {
        this.channel = channel;
    }
    
    @Column(name="temp", precision=12, scale=0)
    public Float getTemp() {
        return this.temp;
    }
    
    public void setTemp(Float temp) {
        this.temp = temp;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="c_time", length=19)
    public Date getCTime() {
        return this.CTime;
    }
    
    public void setCTime(Date CTime) {
        this.CTime = CTime;
    }
    
    @Column(name="vpv1", precision=12, scale=0)
    public Float getVpv1() {
        return this.vpv1;
    }
    
    public void setVpv1(Float vpv1) {
        this.vpv1 = vpv1;
    }
    
    @Column(name="vpv2", precision=12, scale=0)
    public Float getVpv2() {
        return this.vpv2;
    }
    
    public void setVpv2(Float vpv2) {
        this.vpv2 = vpv2;
    }
    
    @Column(name="vpv3", precision=12, scale=0)
    public Float getVpv3() {
        return this.vpv3;
    }
    
    public void setVpv3(Float vpv3) {
        this.vpv3 = vpv3;
    }
    
    @Column(name="lpv1", precision=12, scale=0)
    public Float getLpv1() {
        return this.lpv1;
    }
    
    public void setLpv1(Float lpv1) {
        this.lpv1 = lpv1;
    }
    
    @Column(name="lpv2", precision=12, scale=0)
    public Float getLpv2() {
        return this.lpv2;
    }
    
    public void setLpv2(Float lpv2) {
        this.lpv2 = lpv2;
    }
    
    @Column(name="lpv3", precision=12, scale=0)
    public Float getLpv3() {
        return this.lpv3;
    }
    
    public void setLpv3(Float lpv3) {
        this.lpv3 = lpv3;
    }
    
    @Column(name="vac1", precision=12, scale=0)
    public Float getVac1() {
        return this.vac1;
    }
    
    public void setVac1(Float vac1) {
        this.vac1 = vac1;
    }
    
    @Column(name="vac2", precision=12, scale=0)
    public Float getVac2() {
        return this.vac2;
    }
    
    public void setVac2(Float vac2) {
        this.vac2 = vac2;
    }
    
    @Column(name="vac3", precision=12, scale=0)
    public Float getVac3() {
        return this.vac3;
    }
    
    public void setVac3(Float vac3) {
        this.vac3 = vac3;
    }
    
    @Column(name="lac1", precision=12, scale=0)
    public Float getLac1() {
        return this.lac1;
    }
    
    public void setLac1(Float lac1) {
        this.lac1 = lac1;
    }
    
    @Column(name="lac2", precision=12, scale=0)
    public Float getLac2() {
        return this.lac2;
    }
    
    public void setLac2(Float lac2) {
        this.lac2 = lac2;
    }
    
    @Column(name="lac3", precision=12, scale=0)
    public Float getLac3() {
        return this.lac3;
    }
    
    public void setLac3(Float lac3) {
        this.lac3 = lac3;
    }
    
    @Column(name="pac1", precision=12, scale=0)
    public Float getPac1() {
        return this.pac1;
    }
    
    public void setPac1(Float pac1) {
        this.pac1 = pac1;
    }
    
    @Column(name="pac2", precision=12, scale=0)
    public Float getPac2() {
        return this.pac2;
    }
    
    public void setPac2(Float pac2) {
        this.pac2 = pac2;
    }
    
    @Column(name="pac3", precision=12, scale=0)
    public Float getPac3() {
        return this.pac3;
    }
    
    public void setPac3(Float pac3) {
        this.pac3 = pac3;
    }
    
    @Column(name="fac", precision=12, scale=0)
    public Float getFac() {
        return this.fac;
    }
    
    public void setFac(Float fac) {
        this.fac = fac;
    }
    
    @Column(name="today_ene", precision=12, scale=0)
    public Float getTodayEne() {
        return this.todayEne;
    }
    
    public void setTodayEne(Float todayEne) {
        this.todayEne = todayEne;
    }
    
    @Column(name="total_ene", precision=12, scale=0)
    public Float getTotalEne() {
        return this.totalEne;
    }
    
    public void setTotalEne(Float totalEne) {
        this.totalEne = totalEne;
    }




}


