package qingyun.ele.domain.db;
// Generated 2017-4-17 14:45:18 by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DicDic generated by hbm2java
 */
@Entity
@Table(name = "dic_dic", catalog = "ele")
public class DicDic implements java.io.Serializable {

	private Long id;
	private String name;
	private String descr;
	private Set<Dic> dics = new HashSet<Dic>(0);

	public DicDic() {
	}

	public DicDic(Long id) {
		this.id = id;
	}

	public DicDic(Long id, String name, String descr, Set<Dic> dics) {
		this.id = id;
		this.name = name;
		this.descr = descr;
		this.dics = dics;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "descr", length = 64)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "dicDic")
	public Set<Dic> getDics() {
		return this.dics;
	}

	public void setDics(Set<Dic> dics) {
		this.dics = dics;
	}

}
