package qingyun.ele.domain.db;
// Generated 2017-6-25 15:59:02 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InverterAlert generated by hbm2java
 */
@Entity
@Table(name="inverter_alert"
    ,catalog="ele"
)
public class InverterAlert  implements java.io.Serializable {


     private Long id;
     private String inverterSn;
     private String info;
     private String code;
     private Date ss;
     private Date end;
     private Long status;

    public InverterAlert() {
    }

	
    public InverterAlert(Long id) {
        this.id = id;
    }
    public InverterAlert(Long id, String inverterSn, String info, String code, Date ss, Date end, Long status) {
       this.id = id;
       this.inverterSn = inverterSn;
       this.info = info;
       this.code = code;
       this.ss = ss;
       this.end = end;
       this.status = status;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="inverter_sn", length=64)
    public String getInverterSn() {
        return this.inverterSn;
    }
    
    public void setInverterSn(String inverterSn) {
        this.inverterSn = inverterSn;
    }
    
    @Column(name="info", length=128)
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    
    @Column(name="code", length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ss", length=19)
    public Date getSs() {
        return this.ss;
    }
    
    public void setSs(Date ss) {
        this.ss = ss;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end", length=19)
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }
    
    @Column(name="status")
    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }




}


