package qingyun.ele.domain.db;
// Generated 2017-4-17 14:45:18 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Loan generated by hbm2java
 */
@Entity
@Table(name = "loan", catalog = "ele")
public class Loan implements java.io.Serializable {

	private Long id;
	private String code; // 编号
	private String bank; // 贷款银行
	private Long duration; // 贷款年限 来至跟踪单
	private String capacity;// 实际容量 form2
	private Long radio; // 贷款比例
	private Float amount; // 贷款金额
	private Float amountPermonth; // 每月还款金额 跟踪单
	private String paymentTime; // 每月还款时间 跟踪单
	private Float unitPrice; // 度电单价
	private Float subsidyPrice; // 补贴价格
	private Float estimateCapacity; // 预估发电量
	private Float estimateIncomePermonth; // 预估月收入
	private Float estimateIncomePeryear; // 预估年收入
	private Float actCapacity; // 实际发电量
	private Float actIncomePermonth; // 实际月收入
	private Float actIncomePeryear;// 实际年收入
	private Float recharge;// 充值金额
	private Float balance;// 贷款账户余额
	private Float risk;// 预测还贷风险
	private Long idProject;

	private String c1;
	private String c2;
	private String c3;
	private String content;

	@Column(name = "id_project")
	public Long getIdProject() {
		return idProject;
	}

	public void setIdProject(Long idProject) {
		this.idProject = idProject;
	}

	public Loan() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "code", length = 64)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "bank", length = 64)
	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	 @Column(name = "duration")
//	@Transient
	public Long getDuration() {
		return this.duration;
	}

	public void setDuration(Long duration) {
		this.duration = duration;
	}

	// @Column(name = "capacity")
	@Transient
	public String getCapacity() {
		return this.capacity;
	}

	public void setCapacity(String capacity) {
		this.capacity = capacity;
	}

	@Column(name = "radio")
	public Long getRadio() {
		return this.radio;
	}

	public void setRadio(Long radio) {
		this.radio = radio;
	}

	//@Transient
	@Column(name = "amount", precision = 12, scale = 0)
	public Float getAmount() {
		return this.amount;
	}

	public void setAmount(Float amount) {
		this.amount = amount;
	}

	 @Column(name = "amount_permonth", precision = 12, scale = 0)
	public Float getAmountPermonth() {
		return this.amountPermonth;
	}

	public void setAmountPermonth(Float amountPermonth) {
		this.amountPermonth = amountPermonth;
	}

	@Column(name = "payment_time", length = 20)
	public String getPaymentTime() {
		return this.paymentTime;
	}

	public void setPaymentTime(String paymentTime) {
		this.paymentTime = paymentTime;
	}

	@Column(name = "unit_price", precision = 12, scale = 0)
	public Float getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(Float unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "subsidy_price", precision = 12, scale = 0)
	public Float getSubsidyPrice() {
		return this.subsidyPrice;
	}

	public void setSubsidyPrice(Float subsidyPrice) {
		this.subsidyPrice = subsidyPrice;
	}

	@Column(name = "estimate_capacity", precision = 12, scale = 0)
	public Float getEstimateCapacity() {
		return this.estimateCapacity;
	}

	public void setEstimateCapacity(Float estimateCapacity) {
		this.estimateCapacity = estimateCapacity;
	}

	@Column(name = "estimate_income_permonth", precision = 12, scale = 0)
	public Float getEstimateIncomePermonth() {
		return this.estimateIncomePermonth;
	}

	public void setEstimateIncomePermonth(Float estimateIncomePermonth) {
		this.estimateIncomePermonth = estimateIncomePermonth;
	}

	@Column(name = "estimate_income_peryear", precision = 12, scale = 0)
	public Float getEstimateIncomePeryear() {
		return this.estimateIncomePeryear;
	}

	public void setEstimateIncomePeryear(Float estimateIncomePeryear) {
		this.estimateIncomePeryear = estimateIncomePeryear;
	}

	@Column(name = "act_capacity", precision = 12, scale = 0)
	public Float getActCapacity() {
		return this.actCapacity;
	}

	public void setActCapacity(Float actCapacity) {
		this.actCapacity = actCapacity;
	}

	@Column(name = "act_income_permonth", precision = 12, scale = 0)
	public Float getActIncomePermonth() {
		return this.actIncomePermonth;
	}

	public void setActIncomePermonth(Float actIncomePermonth) {
		this.actIncomePermonth = actIncomePermonth;
	}

	@Column(name = "act_income_peryear", precision = 12, scale = 0)
	public Float getActIncomePeryear() {
		return this.actIncomePeryear;
	}

	public void setActIncomePeryear(Float actIncomePeryear) {
		this.actIncomePeryear = actIncomePeryear;
	}

	@Column(name = "recharge", precision = 12, scale = 0)
	public Float getRecharge() {
		return this.recharge;
	}

	public void setRecharge(Float recharge) {
		this.recharge = recharge;
	}

	@Column(name = "balance", precision = 12, scale = 0)
	public Float getBalance() {
		return this.balance;
	}

	public void setBalance(Float balance) {
		this.balance = balance;
	}

	@Column(name = "risk", precision = 12, scale = 0)
	public Float getRisk() {
		return this.risk;
	}

	public void setRisk(Float risk) {
		this.risk = risk;
	}

	@Transient
	public String getC1() {
		return c1;
	}

	public void setC1(String c1) {
		this.c1 = c1;
	}

	@Transient
	public String getC2() {
		return c2;
	}

	public void setC2(String c2) {
		this.c2 = c2;
	}

	@Transient
	public String getC3() {
		return c3;
	}

	public void setC3(String c3) {
		this.c3 = c3;
	}

	@Column(name = "content", length = 16777216)
	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
