package qingyun.ele.domain.db;
// Generated 2017-4-17 14:45:18 by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProjectSteps generated by hbm2java
 */
@Entity
@Table(name = "project_steps", catalog = "ele")
public class ProjectSteps implements java.io.Serializable {

	private Long id;
	private Dic dicByProgress;
	private Users users;
	private Dic dicByDepartment;
	private Dic dicByStatus;
	private Steps steps;
	private Customer customer;
	private String name;
	private Long forcastDays;
	private Long lastedDays;
	private Date start;
	private Date end;
	private Long actDays;
	private String remark;

	private Long sE;
	private Long eE;
	private Long dE;
	private Long dME;
	// private Set<Loan> loans = new HashSet<Loan>(0);
	// private Set<Info> infos = new HashSet<Info>(0);

	public ProjectSteps() {
	}

	public ProjectSteps(Long id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "progress")
	public Dic getDicByProgress() {
		return this.dicByProgress;
	}

	public void setDicByProgress(Dic dicByProgress) {
		this.dicByProgress = dicByProgress;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "department")
	public Dic getDicByDepartment() {
		return this.dicByDepartment;
	}

	public void setDicByDepartment(Dic dicByDepartment) {
		this.dicByDepartment = dicByDepartment;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "status")
	public Dic getDicByStatus() {
		return this.dicByStatus;
	}

	public void setDicByStatus(Dic dicByStatus) {
		this.dicByStatus = dicByStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_step")
	public Steps getSteps() {
		return this.steps;
	}

	public void setSteps(Steps steps) {
		this.steps = steps;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_customer")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "name", length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "forcast_days")
	public Long getForcastDays() {
		return this.forcastDays;
	}

	public void setForcastDays(Long forcastDays) {
		this.forcastDays = forcastDays;
	}

	@Column(name = "lasted_days")
	public Long getLastedDays() {
		return this.lastedDays;
	}

	public void setLastedDays(Long lastedDays) {
		this.lastedDays = lastedDays;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start", length = 19)
	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end", length = 19)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	@Column(name = "act_days")
	public Long getActDays() {
		return this.actDays;
	}

	public void setActDays(Long actDays) {
		this.actDays = actDays;
	}

	@Column(name = "remark", length = 128)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "s_e")
	public Long getsE() {
		return sE;
	}

	public void setsE(Long sE) {
		this.sE = sE;
	}

	@Column(name = "e_e")
	public Long geteE() {
		return eE;
	}

	public void seteE(Long eE) {
		this.eE = eE;
	}

	@Column(name = "d_e")
	public Long getdE() {
		return dE;
	}

	public void setdE(Long dE) {
		this.dE = dE;
	}

	@Column(name = "d_m_e")
	public Long getdME() {
		return dME;
	}

	public void setdME(Long dME) {
		this.dME = dME;
	}

}
