package qingyun.ele.domain.db;
// Generated 2017-4-17 14:45:18 by Hibernate Tools 3.2.2.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolePages generated by hbm2java
 */
@Entity
@Table(name = "role_pages", catalog = "ele")
public class RolePages implements java.io.Serializable {

	private RolePagesId id;
	private Users users;
	private Pages pages;
	private Long seq;

	public RolePages() {
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idRole", column = @Column(name = "id_role", nullable = false)),
			@AttributeOverride(name = "idPage", column = @Column(name = "id_page", nullable = false)) })
	public RolePagesId getId() {
		return this.id;
	}

	public void setId(RolePagesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_role", nullable = false, insertable = false, updatable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_page", nullable = false, insertable = false, updatable = false)
	public Pages getPages() {
		return this.pages;
	}

	public void setPages(Pages pages) {
		this.pages = pages;
	}

	@Column(name = "seq")
	public Long getSeq() {
		return this.seq;
	}

	public void setSeq(Long seq) {
		this.seq = seq;
	}

}
