package qingyun.ele.domain.db;
// Generated 2017-4-17 14:45:18 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RolePagesId generated by hbm2java
 */
@Embeddable
public class RolePagesId implements java.io.Serializable {

	private Long idRole;
	private Long idPage;

	public RolePagesId() {
	}

	public RolePagesId(Long idRole, Long idPage) {
		this.idRole = idRole;
		this.idPage = idPage;
	}

	@Column(name = "id_role", nullable = false)
	public Long getIdRole() {
		return this.idRole;
	}

	public void setIdRole(Long idRole) {
		this.idRole = idRole;
	}

	@Column(name = "id_page", nullable = false)
	public Long getIdPage() {
		return this.idPage;
	}

	public void setIdPage(Long idPage) {
		this.idPage = idPage;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RolePagesId))
			return false;
		RolePagesId castOther = (RolePagesId) other;

		return ((this.getIdRole() == castOther.getIdRole()) || (this.getIdRole() != null
				&& castOther.getIdRole() != null && this.getIdRole().equals(castOther.getIdRole())))
				&& ((this.getIdPage() == castOther.getIdPage()) || (this.getIdPage() != null
						&& castOther.getIdPage() != null && this.getIdPage().equals(castOther.getIdPage())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdRole() == null ? 0 : this.getIdRole().hashCode());
		result = 37 * result + (getIdPage() == null ? 0 : this.getIdPage().hashCode());
		return result;
	}

}
