package qingyun.ele.domain.db;
// Generated 2017-4-17 14:45:18 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RolePagesId generated by hbm2java
 */
@Embeddable
public class RoleLocationsId implements java.io.Serializable {

	private Long idRole;
	private Long idSubSubLocation;

	public RoleLocationsId() {
	}

	public RoleLocationsId(Long idRole, Long idSubSubLocation) {
		this.idRole = idRole;
		this.idSubSubLocation = idSubSubLocation;
	}

	@Column(name = "id_role", nullable = false)
	public Long getIdRole() {
		return this.idRole;
	}

	public void setIdRole(Long idRole) {
		this.idRole = idRole;
	}

	@Column(name = "idSubSubLocation", nullable = false)
	public Long getIdSubSubLocation() {
		return this.idSubSubLocation;
	}

	public void setIdSubSubLocation(Long idSubSubLocation) {
		this.idSubSubLocation = idSubSubLocation;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleLocationsId))
			return false;
		RoleLocationsId castOther = (RoleLocationsId) other;

		return ((this.getIdRole() == castOther.getIdRole()) || (this.getIdRole() != null
				&& castOther.getIdRole() != null && this.getIdRole().equals(castOther.getIdRole())))
				&& ((this.getIdSubSubLocation() == castOther.getIdSubSubLocation())
						|| (this.getIdSubSubLocation() != null && castOther.getIdSubSubLocation() != null
								&& this.getIdSubSubLocation().equals(castOther.getIdSubSubLocation())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdRole() == null ? 0 : this.getIdRole().hashCode());
		result = 37 * result + (getIdSubSubLocation() == null ? 0 : this.getIdSubSubLocation().hashCode());
		return result;
	}

}
