package qingyun.ele.domain.db;
// Generated 2017-4-17 14:45:18 by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dic generated by hbm2java
 */
@Entity
@Table(name = "sign_workflow", catalog = "ele")
public class SignWorkflow implements java.io.Serializable {

	private Long id;
	private String name;

	private String form;

	public SignWorkflow() {
	}

	public SignWorkflow(Long id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "form", length = 64)
	public String getForm() {
		return form;
	}

	public void setForm(String form) {
		this.form = form;
	}

}
