package qingyun.ele.domain.db;
// Generated 2017-4-17 14:45:18 by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dic generated by hbm2java
 */
@Entity
@Table(name = "sign_workflow_steps", catalog = "ele")
public class SignWorkflowSteps implements java.io.Serializable {

	private Long id;
	private String content;
	private Long idSignWorkflow;
	private Long lvl;
	private Long idSignatory;
	private Long idDepartment;
	private Long idRole;
	
	private Long isLoc;

	
	private Long rev;


	public SignWorkflowSteps() {
	}

	public SignWorkflowSteps(Long id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "content", length = 64)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "id_sign_workflow")
	public Long getIdSignWorkflow() {
		return idSignWorkflow;
	}

	public void setIdSignWorkflow(Long idSignWorkflow) {
		this.idSignWorkflow = idSignWorkflow;
	}

	@Column(name = "lvl")
	public Long getLvl() {
		return lvl;
	}

	public void setLvl(Long lvl) {
		this.lvl = lvl;
	}
	@Column(name = "id_signatory")
	public Long getIdSignatory() {
		return idSignatory;
	}

	public void setIdSignatory(Long idSignatory) {
		this.idSignatory = idSignatory;
	}

	@Column(name = "id_department")
	public Long getIdDepartment() {
		return idDepartment;
	}

	public void setIdDepartment(Long idDepartment) {
		this.idDepartment = idDepartment;
	}

	@Column(name = "is_loc")
	public Long getIsLoc() {
		return isLoc;
	}

	public void setIsLoc(Long isLoc) {
		this.isLoc = isLoc;
	}
	

	@Column(name = "id_role")
	public Long getIdRole() {
		return idRole;
	}

	public void setIdRole(Long idRole) {
		this.idRole = idRole;
	}
	@Column(name = "rev")
	public Long getRev() {
		return rev;
	}

	public void setRev(Long rev) {
		this.rev = rev;
	}



}
