package qingyun.ele.domain.db;
// Generated 2017-4-17 14:45:18 by Hibernate Tools 3.2.2.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dic generated by hbm2java
 */
@Entity
@Table(name = "sign_event", catalog = "ele")
public class SignEvent implements java.io.Serializable {

	private Long id;
	private String remark;
	private Long idSignWorkflowSteps;
	private Long idEvent;
	private Long status;  //0拒绝，1签字，2待签字
	private Date signTime;
	
	private Long deleted;
	
	private Long idUser;
	
	
	private String content;
	private Long idSignWorkflow;
	private Long lvl;
	private Long idSignatory;
	private Long idDepartment;
	private Long idRole;
	
	private Long isLoc;


	public SignEvent() {
	}

	public SignEvent(Long id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "remark", length = 64)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "id_sign_workflow_steps")
	public Long getIdSignWorkflowSteps() {
		return idSignWorkflowSteps;
	}

	public void setIdSignWorkflowSteps(Long idSignWorkflowSteps) {
		this.idSignWorkflowSteps = idSignWorkflowSteps;
	}

	@Column(name = "id_event")
	public Long getIdEvent() {
		return idEvent;
	}

	public void setIdEvent(Long idEvent) {
		this.idEvent = idEvent;
	}

	@Column(name = "status")
	public Long getStatus() {
		return status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sign_time", length = 19)
	public Date getSignTime() {
		return signTime;
	}

	public void setSignTime(Date signTime) {
		this.signTime = signTime;
	}
	@Column(name = "deleted")
	public Long getDeleted() {
		return deleted;
	}

	public void setDeleted(Long deleted) {
		this.deleted = deleted;
	}
	@Column(name = "id_user")
	public Long getIdUser() {
		return idUser;
	}

	public void setIdUser(Long idUser) {
		this.idUser = idUser;
	}
	
	@Column(name = "content", length = 64)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "id_sign_workflow")
	public Long getIdSignWorkflow() {
		return idSignWorkflow;
	}

	public void setIdSignWorkflow(Long idSignWorkflow) {
		this.idSignWorkflow = idSignWorkflow;
	}

	@Column(name = "lvl")
	public Long getLvl() {
		return lvl;
	}

	public void setLvl(Long lvl) {
		this.lvl = lvl;
	}
	@Column(name = "id_signatory")
	public Long getIdSignatory() {
		return idSignatory;
	}

	public void setIdSignatory(Long idSignatory) {
		this.idSignatory = idSignatory;
	}

	@Column(name = "id_department")
	public Long getIdDepartment() {
		return idDepartment;
	}

	public void setIdDepartment(Long idDepartment) {
		this.idDepartment = idDepartment;
	}

	@Column(name = "is_loc")
	public Long getIsLoc() {
		return isLoc;
	}

	public void setIsLoc(Long isLoc) {
		this.isLoc = isLoc;
	}
	

	@Column(name = "id_role")
	public Long getIdRole() {
		return idRole;
	}

	public void setIdRole(Long idRole) {
		this.idRole = idRole;
	}

}
